// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr9F5FsV2Hi2va6NuNFM881B_z86cOI3k',
    appId: '1:939207489719:web:a89ff1724c9829b320f532',
    messagingSenderId: '939207489719',
    projectId: 'catalogo-peliculas-android',
    authDomain: 'catalogo-peliculas-android.firebaseapp.com',
    storageBucket: 'catalogo-peliculas-android.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwOjxZIb6wcitaf_5uxYqk1tDISNlqWDE',
    appId: '1:939207489719:android:3d3545881fd9e37720f532',
    messagingSenderId: '939207489719',
    projectId: 'catalogo-peliculas-android',
    storageBucket: 'catalogo-peliculas-android.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr9F5FsV2Hi2va6NuNFM881B_z86cOI3k',
    appId: '1:939207489719:web:9fce00807aca94a020f532',
    messagingSenderId: '939207489719',
    projectId: 'catalogo-peliculas-android',
    authDomain: 'catalogo-peliculas-android.firebaseapp.com',
    storageBucket: 'catalogo-peliculas-android.firebasestorage.app',
  );
}
